Importo librerias

In [1]:
import pandas as pd
import numpy as np
from math import log2

Cargo el archivo

In [6]:
dataset=pd.read_csv("../../Datos/trabajos_ej4_train.csv")
display(dataset)

,Título universitario,Experiencia en el cargo,Cantidad de Trabajos Anteriores,Trabaja actualmente,Obtiene trabajo
0,SI,BAJA,6,SI,SI
1,NO,BAJA,6,NO,NO
2,NO,ALTA,6,NO,NO
3,NO,ALTA,6,NO,NO
4,NO,MEDIA,6,SI,NO
5,SI,BAJA,6,NO,SI
6,NO,BAJA,6,SI,NO
7,NO,ALTA,8,SI,SI
8,SI,ALTA,8,NO,SI
9,NO,MEDIA,8,SI,NO
10,NO,BAJA,6,NO,NO
11,NO,MEDIA,6,NO,NO
12,NO,MEDIA,6,NO,NO
13,SI,ALTA,9,SI,SI
14,NO,MEDIA,9,SI,SI
15,NO,MEDIA,9,NO,SI

Funcion para calcular la entropia

In [3]:
def calcular_entropia(columna_objetivo):
    valores, cuentas = np.unique(columna_objetivo, return_counts=True)
    probabilidades = cuentas / cuentas.sum()
    entropia = -sum(probabilidades * np.log2(probabilidades))
    return entropia

Funcion para calcular la ganancia con respecto al target

In [4]:
def calcular_ganancia_info(df, atributo, objetivo):
    entropia_total = calcular_entropia(df[objetivo])
    valores, cuentas = np.unique(df[atributo], return_counts=True)
    ponderado = sum(
        (cuentas[i] / np.sum(cuentas)) * calcular_entropia(df[df[atributo] == valores[i]][objetivo])
        for i in range(len(valores))
    )
    ganancia = entropia_total - ponderado
    return ganancia, entropia_total